### ISSUE TITLE
Crash on 1.21.1

### ISSUE THREAD

**Issue by BlueStaggo** [0x000006/vertical-bobbing#5]
Running Vertical Bobbing version 1.3
```
[17:03:18] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking player
	at knot/net.minecraft.class_3242.method_14357(class_3242.java:179) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1032) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1132.method_3748(class_1132.java:114) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalAccessError: class net.minecraft.class_1657 tried to access private field net.minecraft.class_1297.field_5952 (net.minecraft.class_1657 and net.minecraft.class_1297 are in unnamed module of loader 'knot' @6d00a15d)
	at knot/net.minecraft.class_1657.handler$zzc000$vertical-bobbing$afterSetMovementSpeed(class_1657.java:2420) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1657.method_6007(class_1657.java:601) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_5773(class_1309.java:2507) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1657.method_5773(class_1657.java:312) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3222.method_14226(class_3222.java:588) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3244.method_18784(class_3244.java:268) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2535.method_10754(class_2535.java:401) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3242.method_14357(class_3242.java:176) ~[client-intermediary.jar:?]
	... 6 more
```

**Comment by 0x000006** [comment]
fixed in v1.3.1
